# Generated by Django 4.2.6 on 2023-10-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourETAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
