# Generated by Django 4.2.6 on 2023-10-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourETAPP', '0002_destination_website_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image',
            field=models.ImageField(default=1, upload_to='package_images/'),
            preserve_default=False,
        ),
    ]
