# Generated by Django 4.2.6 on 2023-10-20 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourETAPP', '0003_package_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='website_link',
        ),
    ]
