# Generated by Django 4.2.6 on 2023-10-20 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourETAPP', '0004_remove_destination_website_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='destination',
        ),
    ]
