# Generated by Django 4.2.6 on 2023-10-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourETAPP', '0005_remove_package_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='ProfilePhoto'),
        ),
    ]
