# Generated by Django 4.2.5 on 2023-10-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourETAPP', '0006_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default=1, upload_to='ProfilePhoto'),
            preserve_default=False,
        ),
    ]
