# Generated by Django 4.2.5 on 2023-10-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourETAPP', '0007_alter_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='package_images/'),
        ),
    ]
