# Generated by Django 4.2.6 on 2023-10-21 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourETAPP', '0009_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='UserProfile',
        ),
    ]
