# Generated by Django 4.2.6 on 2023-10-21 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourETAPP', '0010_rename_profile_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
    ]
