# Generated by Django 4.2.6 on 2023-10-21 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourETAPP', '0012_alter_package_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='image',
            new_name='package_pic',
        ),
    ]
