# Generated by Django 4.2.4 on 2023-10-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourETAPP', '0013_rename_image_package_package_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
